name: Deploy to AWS Lambda

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean install dependencies
        run: npm ci

      - name: Install AWS CDK
        run: npm i -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Synth stack
        run: cdk synth

      - name: Deploy stack
        run: cdk deploy --all --require-approval never
        env:
          DYNAMO_ENDPOINT: ${{ secrets.DYNAMO_ENDPOINT }}
          DYNAMO_TABLE_NAME: ${{ secrets.DYNAMO_TABLE_NAME }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
          STATE_MACHINE_UPDATE_PLAYLISTS_ARN: ${{ secrets.STATE_MACHINE_UPDATE_PLAYLISTS_ARN }}
